### ISSUE TITLE
Exception in deferred callback causes Node process crash

### ISSUE THREAD

**Issue by jblievremont** [braintree/wrap-promise#4]
Dear maintainers,

The unprotected use of `setTimeout` quoted below causes hard Node process crashes when the deferred function throws an exception.

https://github.com/braintree/wrap-promise/blob/952eecaa3f625dcc1687dcf0a897dd718fb3d0df/lib/deferred.js#L8-L10

This happened in one of our Node-based alerting systems, with the log shown below:

    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: /opt/mycompany/sswallboard/node_modules/braintree/lib/braintree/transaction.js:117
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: this.creditCard = new CreditCard(attributes.creditCard);
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: ^
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: TypeError: Cannot read property 'creditCard' of undefined
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: at new Transaction (/opt/mycompany/sswallboard/node_modules/braintree/lib/braintree/transaction.js:117:49)
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: at /opt/mycompany/sswallboard/node_modules/braintree/lib/braintree/gateway.js:108:26
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: at Timeout._onTimeout (/opt/mycompany/sswallboard/node_modules/@braintree/wrap-promise/lib/deferred.js:9:10)
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: at ontimeout (timers.js:498:11)
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: at tryOnTimeout (timers.js:323:5)
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: at Timer.listOnTimeout (timers.js:290:5)
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR! code ELIFECYCLE
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR! errno 1
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR! Wallboard@2.59.0 start: `node start.js`
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR! Exit status 1
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR!
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR! Failed at the Wallboard@2.59.0 start script.
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR! A complete log of this run can be found in:
    Mar 18 17:34:44 wallboard.internal.mycompany.com wallboard.sh[21603]: npm ERR!     /var/opt/mycompany/sswallboard/.npm/_logs/2019-03-18T16_34_44_525Z-debug.log
    Mar 18 17:34:44 wallboard.internal.mycompany.com systemd[1]: sswallboard.service: main process exited, code=exited, status=1/FAILURE

Currently, there is nothing the client code can do to avoid crashing on error, except top-level hacks like the [`uncaughtException` event handler](https://nodejs.org/api/process.html#process_event_uncaughtexception).

My first suggestion to circumvent this issue would be to add an optional `errorHandler` parameter to `deferred`. E.g, if the last argument is is a function, use it as an error handler.

However, since `deferred` is already used in `wrapPromise` to delay a callback function, I am not sure whether the error handler in this case should be the callback itself, or something entirely different - e.g `console.err`.

I'm looking forward to reading what is your take on this issue.
Kind regards - and thank you for your work on the Braintree SDK!

**Comment by demerino** [comment]
@jblievremont Thanks for bringing up this issue, we'll take a look at the issue.

**Comment by yemanaung** [comment]
good for support

**Comment by crookedneighbor** [comment]
I think the best we can do here is log the error to the console.

I thought about having it try/catch and then pass the error back to the original callback, but that doesn't really make sense, because then you're handling an error outside of the initial function in the callback for that function.

Can't really pass in a _separate_ error handler either. (I mean, you can, but the API for that is pretty weird)

Ultimately though, if you want avoid this error, you should use the promise API instead, that way any errors bubble up to the promise instead of crashing the node process.

https://github.com/braintree/wrap-promise/pull/5

**Comment by jblievremont** [comment]
I do appreciate your suggestion to use the promise-based API. And as far as I can tell, this won't work with the stream-based search APIs.

Anyway, thanks for the followup and incoming fix, looking forward to using it!

**Comment by crookedneighbor** [comment]
Yes, because we made the choice to support streams in the search apis, we couldn't make them support promises as well. In the next major version, we'll have to decide if we want to drop stream support or provide a dedicated stream and promise API.

**Comment by crookedneighbor** [comment]
This was released in v2.0.0

Updating the packages that depend on this to use the new version. Will close this issue when the braintree Node SDK has been released with the new version.

**Comment by crookedneighbor** [comment]
v2.0.0 of wrap-promise has been added to v1.17.0 of braintree-node

**Comment by crookedneighbor** [comment]
*2.17.0 of braintree-node

**Comment by Benstone1956** [comment]
Add braintree+node to paymemt window
